version: '3'
services:
    xen-orchestra:
        image: yobasystems/alpine-xen-orchestra:latest
        container_name: xoa
        command: yarn start
        ports:
            - "8000:8080"
        depends_on:
            - redis
        environment:
            - NODE_ENV=production
        volumes:
            - /data/xoa/server:/app/data
    redis:
        container_name: xoa-redis
        image: redis:alpine
        command: redis-server --appendonly yes
        volumes:
            - /data/xoa/redis:/data
