pool:
  vmImage: "ubuntu-latest"

steps:
  - script: echo "Usando Tasks"
    displayName: "Rodar script"
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Usando Tasks no YAML"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '.'
      ArtifactName: 'drop-yaml'
      publishLocation: 'Container'